### ISSUE TITLE
Is this project receiving contributions ??

### ISSUE THREAD

**Issue by RicardoRibeiroRodrigues** [TheAlgorithms/Mojo#3]
**Hello @SatinWukerORIG and @AppleBoiy,**

I would like to contribute to this repository by adding some algorithms. However, I noticed that the Mojo version referenced in the `CONTRIBUTING.md` file is quite outdated. The current version at the time of this issue is 24.4.0. Would it be acceptable to use this newer version for my contributions? 

Please let me know if this is feasible so I can begin working on the algorithms using the latest Mojo version.

Thank you!

**Comment by SatinWukerORIG** [comment]
Hey, thank you for asking this question. It can be a contribution for sure, but contributors who try to change the version or any other configuration should contact the repo owner. I think we should change it to the latest version. If you want to pull request to fix this, make sure to change anywhere on the markdown that conflicts with this change, thank you!
Hope that answers your question 👍

**Comment by RicardoRibeiroRodrigues** [comment]
Hello,

Thank you for your guidance! I’ll reach out to the repo owner to discuss updating the Mojo version. If they approve, I’ll ensure that all relevant markdown files are updated accordingly.

I’ll proceed with the pull request once I have the green light from the owner.

Thanks again for your help!
