### ISSUE TITLE
Updating to the newer versions of Mojo

### ISSUE THREAD

**Issue by RicardoRibeiroRodrigues** [TheAlgorithms/Mojo#4]
Hello,

I’m interested in contributing to this project. However, I noticed that the CONTRIBUTING.md file references an older version of Mojo (0.2.1). The current version available is 24.4.0, and I believe updating to this newer version would be beneficial, as the current version in the documentation is a very early build.

Before proceeding, I wanted to reach out for approval. If agreed, I would be happy to add new algorithms using the newer version and update the markdown files accordingly.

@TheAlgorithms @AnupKumarPanwar

**Comment by SatinWukerORIG** [comment]
@RicardoRibeiroRodrigues Sorry for this late reply. I already updated the requirement on the contribution guideline. This is never a requirement, and you can contribute anytime!

**Comment by RicardoRibeiroRodrigues** [comment]
Thanks for the reply, I'll be contributing some algorithms soon then!
